class CreateMostOftens < ActiveRecord::Migration
  def self.up
    create_table :most_oftens do |t|
	t.integer :m1
	t.integer :m2
	t.integer :m3
	t.integer :m4
	t.integer :m5
	t.integer :m6
	t.integer :m7
	t.integer :m8
	t.integer :m9
	t.integer :m10
	t.integer :m11
	t.integer :m12
	t.integer :m13
	t.integer :m14
	t.integer :m15
	t.integer :m16
	t.integer :m17
	t.integer :m18
	t.integer :m19
	t.integer :m20
	t.integer :m21
	t.integer :m22
	t.integer :m22
	t.integer :m23
	t.integer :m24
	t.integer :m25
	t.integer :m26
	t.integer :m27
	t.integer :m28
	t.integer :m29
	t.integer :m30
	t.integer :m31
	t.integer :m32
	t.integer :m33
	t.integer :m34
	t.integer :m35
	t.integer :m35
	t.integer :m36
	t.integer :m37
	t.integer :m38
	t.integer :m39
	t.integer :m40
	t.integer :m41
	t.integer :m42
	t.integer :sum_m1
	t.integer :sum_m2
	t.integer :sum_m3
	t.integer :sum_m4
	t.integer :sum_m5
	t.integer :sum_m6
	t.integer :sum_m7
	t.integer :sum_m8
	t.integer :sum_m9
	t.integer :sum_m10
	t.integer :sum_m11
	t.integer :sum_m12
	t.integer :sum_m13
	t.integer :sum_m14
	t.integer :sum_m15
	t.integer :sum_m16
	t.integer :sum_m17
	t.integer :sum_m18
	t.integer :sum_m19
	t.integer :sum_m20
	t.integer :sum_m21
	t.integer :sum_m22
	t.integer :sum_m23
	t.integer :sum_m24
	t.integer :sum_m25
	t.integer :sum_m26
	t.integer :sum_m27
	t.integer :sum_m28
	t.integer :sum_m29
	t.integer :sum_m30
	t.integer :sum_m31
	t.integer :sum_m32
	t.integer :sum_m33
	t.integer :sum_m34
	t.integer :sum_m35
	t.integer :sum_m36
	t.integer :sum_m37
	t.integer :sum_m38
	t.integer :sum_m39
	t.integer :sum_m40
	t.integer :sum_m41
	t.integer :sum_m42
	t.integer :result_id
    end
  end

  def self.down
    drop_table :most_oftens
  end
end
